/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddServicesForm: typeof import('./components/form/AddServicesForm.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/TagAccordion copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ServicesFormComponent: typeof import('./components/form/ServicesFormComponent.vue')['default']
    TagAccordion: typeof import('./components/TagAccordion.vue')['default']
    TagAccordionVirtualMachines: typeof import('./components/TagAccordionVirtualMachines.vue')['default']
  }
}
